/*
===========================================================================
catfight -- playerState_t <-> entityState_t.

A player is replicated to *itself* as a playerState (complete, predicted) and
to *everyone else* as an entityState (a subset, interpolated). This file is the
one place that says which playerState fields survive that trip, so the two
representations cannot quietly drift apart.
===========================================================================
*/

#include "cf_shared.h"

/*
========================
CF_PlayerStateToEntityState

snap controls whether the position is sent as a fixed point (for a snapshot) or
as a linear trajectory the client can extrapolate along.
========================
*/
void CF_PlayerStateToEntityState( playerState_t *ps, entityState_t *s, qboolean snap ) {
	int i;

	if ( ps->pm_type == PM_INTERMISSION || ps->pm_type == PM_SPECTATOR ) {
		s->eType = ET_GENERAL;
	} else {
		s->eType = ET_PLAYER;
	}

	s->number = ps->clientNum;

	s->pos.trType = TR_INTERPOLATE;
	VectorCopy( ps->origin, s->pos.trBase );
	if ( snap ) {
		SnapVector( s->pos.trBase );
	}
	// the velocity goes across so the client can smooth between snapshots
	VectorCopy( ps->velocity, s->pos.trDelta );
	if ( snap ) {
		SnapVector( s->pos.trDelta );
	}

	s->apos.trType = TR_INTERPOLATE;
	VectorCopy( ps->viewangles, s->apos.trBase );
	if ( snap ) {
		SnapVector( s->apos.trBase );
	}

	s->angles2[YAW] = ps->movementDir;
	s->legsAnim = ps->legsAnim;
	s->torsoAnim = ps->torsoAnim;
	s->clientNum = ps->clientNum;
	s->eFlags = ps->eFlags;

	s->groundEntityNum = ps->groundEntityNum;

	s->weapon = ps->weapon;

	s->powerups = 0;
	for ( i = 0; i < MAX_POWERUPS; i++ ) {
		if ( ps->powerups[i] ) {
			s->powerups |= 1 << i;
		}
	}

	s->loopSound = ps->loopSound;
	s->generic1 = ps->generic1;

	// events generated by pmove ride along in the entity state so that other
	// clients hear your footsteps too
	if ( ps->externalEvent ) {
		s->event = ps->externalEvent;
		s->eventParm = ps->externalEventParm;
	} else if ( ps->entityEventSequence < ps->eventSequence ) {
		int seq;

		if ( ps->entityEventSequence < ps->eventSequence - MAX_PS_EVENTS ) {
			ps->entityEventSequence = ps->eventSequence - MAX_PS_EVENTS;
		}
		seq = ps->entityEventSequence & ( MAX_PS_EVENTS - 1 );
		s->event = ps->events[seq] | ( ( ps->entityEventSequence & 3 ) << 8 );
		s->eventParm = ps->eventParms[seq];
		ps->entityEventSequence++;
	} else {
		s->event = 0;
		s->eventParm = 0;
	}
}
