/*
===========================================================================
catfight -- client game module, internal header.

cgame draws the world and predicts the local player. It never decides anything:
every fact it shows comes from a server snapshot, and every prediction it makes
gets overwritten the moment the real answer arrives.
===========================================================================
*/

#ifndef CF_CG_LOCAL_H
#define CF_CG_LOCAL_H

#include "../cf_shared/cf_shared.h"
#include "../cf_shared/cf_weapons.h"
#include "../renderercommon/tr_types.h"
#include "../cgame/cg_public.h"
#include "../client/keycodes.h"

#define MAX_LOCAL_ENTITIES 512

typedef struct {
	entityState_t currentState;
	entityState_t nextState;
	qboolean      interpolate;
	qboolean      currentValid;

	vec3_t        lerpOrigin;
	vec3_t        lerpAngles;

	int           previousEvent;   // so one event is not fired twice

	// Set by EV_RELOAD when the slide was locked back, so EV_RELOAD_DONE knows
	// to finish with the slide slamming forward. Per entity, because two people
	// can be reloading different guns at once.
	qboolean      reloadFromEmpty;
} centity_t;

/*
What we know about another player, parsed out of their CS_PLAYERS configstring.
The scoreboard is drawn entirely from these, which is why a client that joins
halfway through a match still has a complete one.
*/
typedef struct {
	qboolean infoValid;

	char     name[MAX_NETNAME];
	team_t   team;

	int      score;
	int      kills;
	int      deaths;
	qboolean eliminated;
} clientInfo_t;

typedef struct {
	int         clientFrame;

	int         clientNum;

	qboolean    demoPlayback;
	qboolean    levelShot;

	// the snapshot we are currently showing, and the one after it if we have
	// it -- entities are interpolated between the two
	snapshot_t *snap;
	snapshot_t *nextSnap;
	snapshot_t  activeSnapshots[2];

	float       frameInterpolation;   // 0..1 between snap and nextSnap

	qboolean    thisFrameTeleport;
	qboolean    nextFrameTeleport;

	int         frametime;            // cg.time - cg.oldTime
	int         time;                 // this is the time value that the client
	                                  // is rendering at, always <= cl.serverTime
	int         oldTime;

	int         latestSnapshotNum;    // the number of snapshots the client system has received
	int         latestSnapshotTime;   // the time of the latest snapshot the client system has received

	// prediction
	playerState_t predictedPlayerState;
	centity_t     predictedPlayerEntity;
	qboolean      validPPS;           // clear until the first call to CG_PredictPlayerState
	int           predictedErrorTime;
	vec3_t        predictedError;

	// view
	refdef_t      refdef;
	vec3_t        refdefViewAngles;
	float         fov;

	// warning shown while we have no snapshot yet
	qboolean      infoScreenShown;

	// scoreboard, held open by +scores
	qboolean      showScores;

	// the last round result we announced, so the banner is shown once per round
	// rather than every frame it is true for
	int           announcedRound;

	// cg.time the last shot of ours connected. Drives the hit marker, which is
	// the only confirmation a player gets that a bullet landed -- a hitscan
	// weapon has no travel time and nothing else to watch.
	int           hitMarkerTime;

	/*
	The postgame: the match is decided and we are sitting on the result until
	the server drops us. cgame holds the key catcher while this is up, so the
	two keys the prompt names are the two keys that do anything.
	*/
	qboolean      postgame;         // the prompt is up and we hold the catcher
	qboolean      postgameChosen;   // a choice was made; the disconnect is coming
} cg_t;

typedef struct {
	qhandle_t white;         // flat 2D quad, tinted at draw time
	qhandle_t charset;       // 16x16 grid bitmap font
	qhandle_t placeholder;   // stand-in marker for entities with no model yet

	/*
	Weapon audio. These are placeholders generated by
	mapping/gen_weapon_sounds.ps1 rather than recordings, and they are here at
	all because a gun with no sound cannot be judged: report, click and the
	two reload cadences are most of what "does this feel right" is made of.
	Dropping real recordings in at the same paths needs no code change.
	*/
	sfxHandle_t fire;
	sfxHandle_t dryFire;
	sfxHandle_t magOut;
	sfxHandle_t magIn;
	sfxHandle_t slideRelease;
	sfxHandle_t impactFlesh;
	sfxHandle_t impactWall;
} cgMedia_t;

typedef struct {
	gameState_t gameState;
	glconfig_t  glconfig;
	float       screenXScale;
	float       screenYScale;

	int         serverCommandSequence;
	int         processedSnapshotNum;

	char        mapname[MAX_QPATH];

	int         levelStartTime;

	// match state, mirrored from CS_MATCH_STATE / CS_SCORES
	matchState_t matchState;
	int          matchStateTime;
	int          matchStateEnd;

	int          roundNumber;
	int          teamRounds[TEAM_NUM_TEAMS];

	clientInfo_t clientinfo[MAX_CLIENTS];

	cgMedia_t   media;
} cgs_t;

extern cg_t  cg;
extern cgs_t cgs;
extern centity_t cg_entities[MAX_GENTITIES];

extern vmCvar_t cg_fov;
extern vmCvar_t cg_drawCrosshair;
extern vmCvar_t cg_nopredict;
extern vmCvar_t cg_showSpeed;
extern vmCvar_t cg_thirdPerson;
extern vmCvar_t cg_thirdPersonRange;

extern vmCvar_t cg_drawScoreboard;
extern vmCvar_t cg_drawStatus;

//
// cg_main.c
//
void QDECL CG_Printf( const char *msg, ... ) Q_PRINTF_FUNC( 1, 2 );
void QDECL CG_Error( const char *msg, ... ) Q_NO_RETURN Q_PRINTF_FUNC( 1, 2 );
const char *CG_ConfigString( int index );
void CG_UpdateCvars( void );
void CG_ParseMatchState( void );
void CG_ParseScores( void );
void CG_NewClientInfo( int clientNum );
const char *CG_TeamName( team_t team );
const float *CG_TeamColor( team_t team );

//
// cg_snapshot.c
//
void CG_ProcessSnapshots( void );

//
// cg_predict.c
//
void CG_PredictPlayerState( void );
void CG_Trace( trace_t *result, const vec3_t start, const vec3_t mins, const vec3_t maxs,
               const vec3_t end, int skipNumber, int mask );
int  CG_PointContents( const vec3_t point, int passEntityNum );

//
// cg_view.c
//
void CG_DrawActiveFrame( int serverTime, stereoFrame_t stereoView, qboolean demoPlayback );

//
// cg_ents.c
//
void CG_AddPacketEntities( void );

//
// cg_draw.c
//
void CG_Draw2D( void );
void CG_DrawInformation( void );
void CG_FillRect( float x, float y, float width, float height, const float *color );
void CG_AdjustFrom640( float *x, float *y, float *w, float *h );
void CG_DrawString( float x, float y, const char *s, float charWidth, float charHeight,
                    const float *color );
void CG_DrawStringCentred( float cx, float y, const char *s, float charWidth, float charHeight,
                           const float *color );

//
// cg_scoreboard.c
//
qboolean CG_DrawScoreboard( void );
void     CG_DrawRoundStatus( void );
void     CG_UpdatePostgame( void );
void     CG_DrawPostgamePrompt( void );
void     CG_PostgameKey( int key );
void     CG_PostgameEventHandling( int event );

//
// cg_event.c
//
void CG_EntityEvent( centity_t *cent, const vec3_t position );
void CG_CheckEvents( centity_t *cent );

//
// cg_servercmds.c
//
void CG_ExecuteNewServerCommands( int latestSequence );

//
// cg_syscalls.c
//
void        trap_Print( const char *fmt );
void        trap_Error( const char *fmt ) Q_NO_RETURN;
int         trap_Milliseconds( void );
void        trap_Cvar_Register( vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags );
void        trap_Cvar_Update( vmCvar_t *vmCvar );
void        trap_Cvar_Set( const char *var_name, const char *value );
void        trap_Cvar_VariableStringBuffer( const char *var_name, char *buffer, int bufsize );
int         trap_Argc( void );
void        trap_Argv( int n, char *buffer, int bufferLength );
void        trap_Args( char *buffer, int bufferLength );
void        trap_SendConsoleCommand( const char *text );
void        trap_AddCommand( const char *cmdName );
void        trap_RemoveCommand( const char *cmdName );
void        trap_SendClientCommand( const char *s );
void        trap_UpdateScreen( void );
void        trap_CM_LoadMap( const char *mapname );
int         trap_CM_PointContents( const vec3_t p, clipHandle_t model );
void        trap_CM_BoxTrace( trace_t *results, const vec3_t start, const vec3_t end,
                              const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask );
clipHandle_t trap_CM_InlineModel( int index );
int         trap_CM_NumInlineModels( void );
void        trap_S_ClearLoopingSounds( qboolean killall );
void        trap_S_Respatialize( int entityNum, const vec3_t origin, vec3_t axis[3], int inwater );
sfxHandle_t trap_S_RegisterSound( const char *sample, qboolean compressed );
void        trap_S_StartLocalSound( sfxHandle_t sfx, int channelNum );
void        trap_S_StartSound( const vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx );
void        trap_R_LoadWorldMap( const char *mapname );
qhandle_t   trap_R_RegisterModel( const char *name );
qhandle_t   trap_R_RegisterShader( const char *name );
qhandle_t   trap_R_RegisterShaderNoMip( const char *name );
void        trap_R_ClearScene( void );
void        trap_R_AddRefEntityToScene( const refEntity_t *re );
void        trap_R_AddLightToScene( const vec3_t org, float intensity, float r, float g, float b );
void        trap_R_RenderScene( const refdef_t *fd );
void        trap_R_SetColor( const float *rgba );
void        trap_R_DrawStretchPic( float x, float y, float w, float h,
                                   float s1, float t1, float s2, float t2, qhandle_t hShader );
void        trap_GetGlconfig( glconfig_t *glconfig );
void        trap_GetGameState( gameState_t *gamestate );
void        trap_GetCurrentSnapshotNumber( int *snapshotNumber, int *serverTime );
qboolean    trap_GetSnapshot( int snapshotNumber, snapshot_t *snapshot );
qboolean    trap_GetServerCommand( int serverCommandNumber );
int         trap_GetCurrentCmdNumber( void );
qboolean    trap_GetUserCmd( int cmdNumber, usercmd_t *ucmd );
void        trap_SetUserCmdValue( int stateValue, float sensitivityScale );
int         trap_Key_IsDown( int keynum );
int         trap_Key_GetCatcher( void );
void        trap_Key_SetCatcher( int catcher );
int         trap_RealTime( qtime_t *qtime );

#endif // CF_CG_LOCAL_H
